// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIFfeCun63TLfiun79unTTzHOpgBKQncw',
    appId: '1:420312075261:web:2e8f04cd2fa14f58886794',
    messagingSenderId: '420312075261',
    projectId: 'cloud-messaging-67408',
    authDomain: 'cloud-messaging-67408.firebaseapp.com',
    storageBucket: 'cloud-messaging-67408.firebasestorage.app',
    measurementId: 'G-85T5LNN04H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0sVqzBi_InWV95HLWBwe6u9_4rh60kH0',
    appId: '1:420312075261:android:f5d8d91a23bfb9b8886794',
    messagingSenderId: '420312075261',
    projectId: 'cloud-messaging-67408',
    storageBucket: 'cloud-messaging-67408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFVZ5BwY2UdFfidFN7gtntNBQMPHHAFfk',
    appId: '1:420312075261:ios:e1b5053be5868315886794',
    messagingSenderId: '420312075261',
    projectId: 'cloud-messaging-67408',
    storageBucket: 'cloud-messaging-67408.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFVZ5BwY2UdFfidFN7gtntNBQMPHHAFfk',
    appId: '1:420312075261:ios:e1b5053be5868315886794',
    messagingSenderId: '420312075261',
    projectId: 'cloud-messaging-67408',
    storageBucket: 'cloud-messaging-67408.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIFfeCun63TLfiun79unTTzHOpgBKQncw',
    appId: '1:420312075261:web:241681f3e658b52d886794',
    messagingSenderId: '420312075261',
    projectId: 'cloud-messaging-67408',
    authDomain: 'cloud-messaging-67408.firebaseapp.com',
    storageBucket: 'cloud-messaging-67408.firebasestorage.app',
    measurementId: 'G-GGCV94NXKG',
  );
}
